title: Hacker-Blog
description: "A Blog For Hackers"
author:
  name: "sevh3n"
  email: "aj.rcelada@gmail.com"
  url: "https://sevh3n.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap


# Custom variables
owner : "sevh3n"
year : "2025"
