title: Hacker-Blog
description: "A Blog For Hackers"
author:
  name: "sevh3n"
  email: "aj.rcelada@gmail.com"
  url: "https://ashishchaudhary.in/hacker-blog"

baseurl: /

source: .
destination: ./_site
permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives

jekyll-archives:
  enabled: true
  layouts:
    category: category
  permalinks:
    category: /category/:name/

# Custom variables
owner : "sevh3n"
year : "2025"
